backend:
  name: github
  repo: Brightside-Technologies/brightsidetech.io
  branch: master

media_folder: "src/jekyll/assets/images" # Folder where user uploaded files should go
public_folder: "assets/images"
collections:
  - name: "content"
    label: "Site Content"
    delete: false
    description: Content for site
    extension: "json"
    files:

      - label: "Portfolio"
        name: "portfolio"
        delete: false,
        description: "List of our work"
        file: "src/jekyll/_data/portfolio.json"
        fields:
          - name: portfolio
            label: Portfolio
            widget: list
            fields:
              - {label: "Client", name: "client", widget: "string"}
              - {label: "Description", name: "description", widget: "markdown"}
              - {label: "Url", name: "url", widget: "string"}
              - {label: "Thumbnail", name: "image", widget: "image", required: true, tagname: ""}
        
      - label: "Team"
        name: "team"
        delete: false,
        description: "Meet the Team"
        file: "src/jekyll/_data/team.json"
        fields:
          - name: team
            label: Team
            widget: list
            fields:
              - {label: "Name", name: "name", widget: "string"}
              - {label: "Title", name: "title", widget: "string"}
              - {label: "About", name: "about", widget: "markdown"}
              - {label: "Picture", name: "image", widget: "image", required: false, default: "assets/images/profile.jpg"}
              - label: "Contact"
                name: "contact"
                widget: list
                allow_add: true
                fields:
                    - {label: "Type", name: "type", widget: "select", options: ["-Select Type-", "Email", "Phone", "Facebook", "Twitter", "LinkedIn"]}
                    - {label: Value, name: value, widget: string}
  
      - label: "Testimonials"
        name: "testimonials"
        widget: "list"
        file: "src/jekyll/_data/testimonials.json"
        fields:
          - {label: Quote, name: quote, widget: markdown}
          - label: Author
            name: author
            widget: object
            fields:
              - {label: Name, name: name, widget: string}
              - {label: Avatar, name: avatar, widget: image}

      - label: "Content"
        name: "content"
        widget: object
        desctiption: Contains About Us, What We Do, etc
        file: src/jekyll/_data/content.json
        fields:
          - {label: Navbar Logo, name: navbarLogo, widget: image}
          - {label: Hero Text, name: heroText, widget: text}
          - {label: Hero Image, name: heroImage, widget: image}
          - {label: Lead, name: lead, widget: text}
          - {label: About Brightside Tech, name: aboutBrightsideTech, widget: markdown, class: test}
          - {label: Who We Are, name: whoWeAre, widget: markdown}
          - label: What We Do
            name: whatWeDo
            widget: object
            fields:
              - {label: Text, name: text, widget: markdown}
              - label: Services
                name: services
                widget: list
                fields: 
                  - {label: Service Title, name: title, widget: string}
                  - {label: Service Image, name: image, widget: image, default: ""}       
                  - {label: Description, name: description, widget: markdown}
          
  - name: metadata
    label: "Site Metadata"
    delete: false
    description: Site metadata and global settings
    extension: json
    files:
      - name: metadata
        label: Site Metadata
        file: src/jekyll/_data/metadata.json
        editor:
          preview: false
        fields:
          - {label: "Site Title", name: "title", widget: "string"}
          - {label: "Author", name: "author", widget: "string"}
          - {label: "Favicon", name: "favicon", widget: "image", required: false}
          - {label: "Site Type", name: "type", widget: "string", default: website}
          - {label: "Site Description", name: "description", widget: "text"}
          - {label: "Site Thumbnail", name: "image", widget: "image", required: false}
          - {label: "Site Url", name: "url", widget: "string", required: false}
          - {label: "Facebook Url", name: "facebookUrl", widget: "string", required: false}
          - {label: "Twitter Url", name: "twitterUrl", widget: "string", required: false}
          - {label: "Contact Email", name: "email", widget: "string", required: false}
          - {label: "Contact Phone Number", name: "phone", widget: "string", required: false}
          - {label: "Google Analytics ID", name: "googleAnalyticsId", widget: "string", required: false}
          - label: Site Keywords (for SEO)
            name: keywords
            widget: list
            allow_add: true
